### ISSUE TITLE
推理失败

### ISSUE THREAD

**Issue by 1994** [QwenLM/qwen.cpp#13]
Assertion failed: (encoder_.size() != decoder_.size() && "Encoder and decoder must be of equal length; maybe you had duplicate token indices in your encoder?"), function tiktoken, file tiktoken.h, line 139

**Comment by simonJJJ** [comment]
Do you use the ```qwen.tiktoken``` file?

**Comment by 1994** [comment]
> Do you use the `qwen.tiktoken` file?

指定了的

![image](https://github.com/QwenLM/qwen.cpp/assets/3808487/54a582f3-80bd-4d0e-b8b0-f83f899a1a3a)

**Comment by 1994** [comment]
奇怪，重新编译后不出现了
