### ISSUE TITLE
Could you provice converted qwen7b-ggml.bin?

### ISSUE THREAD

**Issue by weizhenhuan** [QwenLM/qwen.cpp#21]
For some network problem，I fail to download model weights from huggingface even using proxy.  Could you provice converted qwen7b-ggml.bin? Or some other methods to solve the network problem?

**Comment by simonJJJ** [comment]
Hi @weizhenhuan, you can download from [modelscope](https://modelscope.cn/models/qwen/Qwen-7B-Chat/files).
