### ISSUE TITLE
ModuleNotFoundError: No module named 'qwen_cpp._C'

### ISSUE THREAD

**Issue by dlutsniper** [QwenLM/qwen.cpp#22]
after install Python Binding，i try to run python code, but has a error: 

ModuleNotFoundError: No module named 'qwen_cpp._C'

```
from qwen_cpp import Pipeline

pipeline = Pipeline(model_path="/Users/wy/dev-qwen/qwen.cpp/qwen14b-ggml.bin", tiktoken_path="/Users/wy/dev-qwen/models/Qwen-14B-Chat/qwen.tiktoken")

res = pipeline.chat(history=["你是谁"])
print(res)
```

detail log
```
/Users/wy/dev-qwen/qwen.cpp/venv/bin/python /Users/wy/dev-qwen/qwen.cpp/venv/lib/python3.11/site-packages/qwen_cpp/__init__.py 
Traceback (most recent call last):
  File "/Users/wy/dev-qwen/qwen.cpp/venv/lib/python3.11/site-packages/qwen_cpp/__init__.py", line 5, in <module>
    import qwen_cpp._C as _C
  File "/Users/wy/dev-qwen/qwen.cpp/qwen_cpp/__init__.py", line 5, in <module>
    import qwen_cpp._C as _C
ModuleNotFoundError: No module named 'qwen_cpp._C'
```
<img width="1279" alt="图片" src="https://github.com/QwenLM/qwen.cpp/assets/30826840/05faa656-41f5-492e-9744-539fc4884bd5">

**Comment by simonJJJ** [comment]
Hi @dlutsniper, how did you install python bindings?

**Comment by dlutsniper** [comment]
> Hi @dlutsniper, how did you install python bindings?
on my macbookpro, 
pip install -U qwen-cpp

**Comment by mashuiping** [comment]
不要在 qwen.cpp 根目录下执行，换个目录

**Comment by simonJJJ** [comment]
> 不要在 qwen.cpp 根目录下执行，换个目录

exactly!

**Comment by dlutsniper** [comment]
> 不要在 qwen.cpp 根目录下执行，换个目录
Certainly, change the directory, install the dependencies using the default Miniconda environment, and i can call it through Python code.
确实换个目录，使用默认的miniconda环境安装依赖，通过python代码可以调用啦
<img width="1280" alt="图片" src="https://github.com/QwenLM/qwen.cpp/assets/30826840/fec9402a-496b-4ee2-b3ce-19388a8d0f24">
<img width="1280" alt="图片" src="https://github.com/QwenLM/qwen.cpp/assets/30826840/52acb88f-a7e2-4273-9d77-d37ae6bbfa02">

**Comment by dlutsniper** [comment]
Certainly, change the directory, install the dependencies using the default Miniconda environment, and i can call it through Python code.
确实换个目录，使用默认的miniconda环境安装依赖，通过python代码可以调用啦
<img width="1280" alt="图片" src="https://github.com/QwenLM/qwen.cpp/assets/30826840/1bca186a-df2d-4407-b11e-6be22bfc08d1">
<img width="1280" alt="图片" src="https://github.com/QwenLM/qwen.cpp/assets/30826840/15317cba-d976-433b-85a6-c0aa65e91b2a">

**Comment by zzzcccxx** [comment]
请问如果我不想在gpu上运行，如何在cpu上运行呢？
